import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'uk';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('prosthemap-lang');
    return (saved === 'uk' ? 'uk' : 'en') as Language;
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('prosthemap-lang', lang);
  };

  const t = (key: string): string => {
    const keys = key.split('.');
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    let value: any = translations[language];
    for (const k of keys) {
      value = value?.[k];
    }
    return (typeof value === 'string' ? value : key);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// ──────────────────────────────────────
// TRANSLATIONS
// ──────────────────────────────────────
const translations: Record<Language, Record<string, unknown>> = {
  en: {
    nav: {
      home: 'Home',
      about: 'About',
      account: 'Account',
      dashboard: 'Dashboard',
      signOut: 'Sign Out',
      login: 'Login',
      signUp: 'Sign Up',
    },
    index: {
      heroTitle1: 'Connecting Ukrainian Amputees with ',
      heroTitle2: 'Essential Support',
      heroSubtitle: 'Receive a curated roadmap to assist you throughout your prosthetic journey.',
      getStarted: 'Get Started',
      learnMore: 'Learn More',
      footer: '© 2025 Prosthemap. Supporting Ukraine\'s heroes.',
    },
    about: {
      title: 'About This Project',
      intro: 'We began this project with a simple thought, that thousands of amputees in Ukraine have to face a fragmented and overwhelming mass of resources to achieve funding and rehabilitation. The information does exist scattered across government portals, NGO websites, and clinical networks, however accessing it requires a lot of time, language fluency, and institutional knowledge which most can\'t obtain. This project is something that helps bridge the gap.',
      whoWeAre: 'Who We Are',
      foundersCaption: 'Harley Thorpe and Victor Pivtoran, two Computer Science students at Western University devoted to make a positive impact.',
      whoWeAreP1: 'Although we don\'t have special expertise in prosthetics, we knew our technical skills would suffice. We have a background in building projects: programming, designing systems, precise planning, troubleshooting, and teamwork. This project is what pushed us to use these skills to the max, while ensuring our goals align with the Protez Foundation.',
      whoWeAreP2: 'We don\'t pretend to have all the answers. What we do is fully commit to learning to those who know more than we do, and build tools that actually end up being useful.',
      whatGuidesUs: 'What Guides Us',
      contributionTitle: 'Contribution',
      contributionText: 'We aim to work on things bigger than ourselves, to really make a positive impact on the world. Just because we are students doesn\'t mean we can have a big influence.',
      responsibilityTitle: 'Responsibility',
      responsibilityText: 'A project like this comes with obligations. We understand that this is something that people will rely on, especially those who are vulnerable. It is our duty to get things right in this project - to be accurate, effective, and careful.',
      learningTitle: 'Learning',
      learningText: 'At the core, we wanted to take on this challenge of a project for the learning experience. Every failed approach at this website taught us something, and grew humility into how we work.',
      lookingForward: 'Looking Forward',
      lookingForwardP1: 'We plan to continue updating and improving this website for years on end, continuously providing the best results for those in need. The platform will evolve from situations in Ukraine changing and user feedback.',
      lookingForwardP2: 'If you\'re a clinician, rehabilitation specialist, or someone with lived experience who would like to contribute your expertise, we would be grateful to hear from you. If you\'re a researcher, developer, or designer interested in collaborating, we\'re open to that as well. And if you simply want to follow our progress, you\'re welcome to do so. We\'ll keep building.',
    },
    assessment: {
      title: 'Personalized Assessment',
      subtitle: 'Help us understand your situation to provide the most relevant resources',
      stepOf: 'Step {step} of {total}',
      step1Title: 'What is your status?',
      step1Subtitle: 'This helps us provide resources specific to your situation.',
      military: 'Military',
      civilian: 'Civilian',
      step2Title: 'Pre-Surgery Information',
      step2Subtitle: 'What type of amputation procedure applies to your situation?',
      planned: 'Planned amputation',
      emergency: 'Emergency amputation (trauma)',
      step3Title: 'What type of amputation?',
      step3Subtitle: 'Select the limb type and level of amputation.',
      limbType: 'Limb Type',
      upperLimb: 'Upper Limb',
      lowerLimb: 'Lower Limb',
      amputationLevel: 'Amputation Level',
      shoulderDisarticulation: 'Shoulder disarticulation',
      aboveElbow: 'Above elbow',
      belowElbow: 'Below elbow',
      wrist: 'Wrist',
      fingers: 'Finger(s)',
      hipDisarticulation: 'Hip disarticulation',
      aboveKnee: 'Above knee',
      belowKnee: 'Below knee',
      partialFoot: 'Partial foot',
      step4Title: 'Select the stage you are at right now',
      step4Subtitle: 'This helps us provide the most relevant next steps for your journey.',
      preSurgical: 'Pre-Surgical',
      acutePostSurgical: 'Acute Post-Surgical',
      inPatientPostSurgical: 'In-Patient Post-Surgical',
      rehabilitation: 'Rehabilitation and Assistive Device Prescription/Selection',
      preProsthetic: 'Pre-Prosthetic Rehabilitation (For Prosthetic Users)',
      prostheticFitting: 'Prosthetics Provider Selection and Prosthetic Fitting',
      prostheticTraining: 'Prosthetic Training',
      communityReintegration: 'Community Reintegration (Potential Job Retraining, Etc)',
      step5Title: 'Which region are you from?',
      step5Subtitle: 'This helps us prioritize clinics and resources in your area.',
      step6Title: 'Additional information',
      step6Subtitle: 'Share any other details that might help us provide better support (optional).',
      additionalLabel: 'Additional comments or concerns',
      additionalPlaceholder: 'For example: mobility challenges, living situation, family support, employment needs...',
      back: 'Back',
      next: 'Next',
      complete: 'Complete',
      notAuthenticated: 'Not authenticated',
      notAuthenticatedDesc: 'Please log in to save your assessment.',
      assessmentComplete: 'Assessment Complete',
      assessmentCompleteDesc: 'Your personalized roadmap has been saved.',
      errorSaving: 'Error Saving',
      errorSavingDesc: 'There was a problem saving your assessment. Please try again.',
    },
    resources: {
      retakeAssessment: 'Retake Assessment',
      yourRecoveryRoadmap: 'Your Recovery Roadmap',
      sections: 'Sections',
      resourcesAvailable: 'Resources',
      actionSteps: 'Action Steps',
      yourJourney: 'Your Personalized Journey',
      yourJourneySubtitle: 'Follow these steps to navigate your recovery',
      loading: 'Loading your roadmap...',
      completeFirst: 'Complete Your Assessment First',
      completeFirstDesc: 'To generate your personalized recovery roadmap, please complete the assessment survey.',
      startAssessment: 'Start Assessment',
      learnMore: 'Learn more',
      visitWebsite: 'Visit Website',
      yourRegion: 'Your Region',
      nearby: 'Nearby',
      step: 'Step',
      criticalPriority: 'Critical Priority',
      highPriority: 'High Priority',
      onTrack: 'On Track',
      goodProgress: 'Good Progress',
    },
    dashboard: {
      welcomeBack: 'Welcome back',
      subtitle: 'Your personalized prosthetic assistance dashboard',
      yourProfile: 'Your Profile',
      name: 'Name',
      email: 'Email',
      languageLabel: 'Language',
      notSet: 'Not set',
      english: 'English',
      ukrainian: 'Ukrainian',
      assessmentStatus: 'Assessment Status',
      completed: 'Completed',
      injuryTiming: 'Injury Timing',
      retakeAssessment: 'Retake Assessment',
      noAssessment: 'You haven\'t completed an assessment yet.',
      startAssessment: 'Start Assessment',
      yourRoadmap: 'Your Personalized Roadmap',
      viewRoadmapDesc: 'View your customized path to prosthetic assistance',
      viewRoadmap: 'View Roadmap',
    },
    auth: {
      welcomeBack: 'Welcome Back',
      createAccount: 'Create Account',
      resetPassword: 'Reset Password',
      signInSubtitle: 'Sign in to access your personalized roadmap',
      signUpSubtitle: 'Join us to get personalized prosthetic assistance',
      resetSubtitle: 'Enter your email to receive a reset link',
      fullName: 'Full Name',
      fullNamePlaceholder: 'Enter your full name',
      emailLabel: 'Email',
      emailPlaceholder: 'Enter your email',
      passwordLabel: 'Password',
      passwordPlaceholder: 'Enter your password',
      forgotPassword: 'Forgot password?',
      signIn: 'Sign In',
      signUpBtn: 'Create Account',
      sendResetLink: 'Send Reset Link',
      noAccount: 'Don\'t have an account?',
      haveAccount: 'Already have an account?',
      signUpLink: 'Sign up',
      signInLink: 'Sign in',
      loginFailed: 'Login Failed',
      invalidCredentials: 'Invalid email or password. Please try again.',
      accountExists: 'Account Exists',
      accountExistsDesc: 'An account with this email already exists. Please log in instead.',
      signUpFailed: 'Sign Up Failed',
      accountCreated: 'Account Created!',
      accountCreatedDesc: 'Welcome to Ukraine Prosthetic Aid. You can now access your personalized dashboard.',
      resetFailed: 'Reset Failed',
      checkEmail: 'Check Your Email',
      checkEmailDesc: 'If an account exists with this email, you will receive a password reset link.',
    },
    disclaimer: {
      title: 'Important Disclaimer',
      body: 'The information on this website should not be considered as medical advice and is for informational purposes only. You should always consult with a specialist before making decisions.',
      accept: 'I Understand',
    },
    notFound: {
      title: '404',
      message: 'Oops! Page not found',
      backHome: 'Return to Home',
    },
    prostheticOptions: {
      title: 'Prosthetic Options',
      titleDiscuss: 'Prosthetic Options to Discuss',
      consultMessage: 'Discuss prosthetic options with your healthcare provider and prosthetist. They will recommend suitable options based on your specific situation.',
      basedOnSituation: 'Based on your situation, you may want to discuss these options with your healthcare provider:',
      notMedicalAdvice: 'This is not medical advice. Always consult with qualified healthcare professionals before making decisions about prosthetics.',
    },
    regionSelector: {
      searchPlaceholder: 'Search regions / Пошук регіонів...',
      noResults: 'No regions found matching',
      selected: 'Selected',
    },
  },
  uk: {
    nav: {
      home: 'Головна',
      about: 'Про нас',
      account: 'Акаунт',
      dashboard: 'Панель',
      signOut: 'Вийти',
      login: 'Увійти',
      signUp: 'Реєстрація',
    },
    index: {
      heroTitle1: 'Зв\'язуємо українських ампутантів з ',
      heroTitle2: 'необхідною підтримкою',
      heroSubtitle: 'Отримайте персоналізований план допомоги на шляху до протезування.',
      getStarted: 'Почати',
      learnMore: 'Дізнатися більше',
      footer: '© 2025 Prosthemap. Підтримуємо героїв України.',
    },
    about: {
      title: 'Про цей проєкт',
      intro: 'Ми розпочали цей проєкт з простої думки: тисячі ампутантів в Україні змушені стикатися з розрізненою та надмірною масою ресурсів для отримання фінансування та реабілітації. Інформація існує — розкидана по державних порталах, сайтах НУО та клінічних мережах, але доступ до неї потребує багато часу, мовних навичок та інституційних знань, яких більшість не може отримати. Цей проєкт допомагає подолати цю прірву.',
      whoWeAre: 'Хто ми',
      foundersCaption: 'Харлі Торп та Віктор Півторан — два студенти комп\'ютерних наук у Західному університеті, які прагнуть зробити позитивний вплив.',
      whoWeAreP1: 'Хоча ми не маємо спеціальних знань у протезуванні, ми знали, що наших технічних навичок буде достатньо. Ми маємо досвід у створенні проєктів: програмування, проєктування систем, точне планування, усунення несправностей та командна робота. Цей проєкт підштовхнув нас використовувати ці навички на максимум, забезпечуючи відповідність наших цілей Фонду Протез.',
      whoWeAreP2: 'Ми не претендуємо на те, що маємо всі відповіді. Ми повністю віддані навчанню у тих, хто знає більше, та створюємо інструменти, які справді виявляються корисними.',
      whatGuidesUs: 'Що нас направляє',
      contributionTitle: 'Внесок',
      contributionText: 'Ми прагнемо працювати над речами більшими за нас самих, щоб справді позитивно вплинути на світ. Те, що ми студенти, не означає, що ми не можемо мати великий вплив.',
      responsibilityTitle: 'Відповідальність',
      responsibilityText: 'Такий проєкт несе зобов\'язання. Ми розуміємо, що на це покладатимуться люди, особливо вразливі. Наш обов\'язок — зробити все правильно: точно, ефективно та обережно.',
      learningTitle: 'Навчання',
      learningText: 'В основі ми хотіли взятися за цей виклик заради навчального досвіду. Кожен невдалий підхід до цього сайту навчив нас чомусь і виростив смирення в нашій роботі.',
      lookingForward: 'Погляд у майбутнє',
      lookingForwardP1: 'Ми плануємо продовжувати оновлювати та вдосконалювати цей сайт роками, постійно надаючи найкращі результати для тих, хто потребує. Платформа еволюціонуватиме відповідно до змін в Україні та відгуків користувачів.',
      lookingForwardP2: 'Якщо ви клініцист, спеціаліст з реабілітації або людина з відповідним досвідом, яка хоче поділитися своїми знаннями — ми будемо вдячні. Якщо ви дослідник, розробник або дизайнер, зацікавлений у співпраці — ми відкриті. Якщо ви просто хочете стежити за нашим прогресом — ласкаво просимо. Ми продовжуємо будувати.',
    },
    assessment: {
      title: 'Персоналізована оцінка',
      subtitle: 'Допоможіть нам зрозуміти вашу ситуацію для надання найбільш відповідних ресурсів',
      stepOf: 'Крок {step} з {total}',
      step1Title: 'Який ваш статус?',
      step1Subtitle: 'Це допомагає нам надати ресурси, специфічні для вашої ситуації.',
      military: 'Військовий',
      civilian: 'Цивільний',
      step2Title: 'Доопераційна інформація',
      step2Subtitle: 'Який тип ампутації стосується вашої ситуації?',
      planned: 'Планова ампутація',
      emergency: 'Екстрена ампутація (травма)',
      step3Title: 'Який тип ампутації?',
      step3Subtitle: 'Виберіть тип кінцівки та рівень ампутації.',
      limbType: 'Тип кінцівки',
      upperLimb: 'Верхня кінцівка',
      lowerLimb: 'Нижня кінцівка',
      amputationLevel: 'Рівень ампутації',
      shoulderDisarticulation: 'Екзартикуляція плечового суглоба',
      aboveElbow: 'Вище ліктя',
      belowElbow: 'Нижче ліктя',
      wrist: 'Зап\'ясток',
      fingers: 'Палець(і)',
      hipDisarticulation: 'Екзартикуляція кульшового суглоба',
      aboveKnee: 'Вище коліна',
      belowKnee: 'Нижче коліна',
      partialFoot: 'Часткова стопа',
      step4Title: 'Виберіть етап, на якому ви зараз перебуваєте',
      step4Subtitle: 'Це допомагає нам надати найбільш відповідні наступні кроки.',
      preSurgical: 'Доопераційний',
      acutePostSurgical: 'Гострий післяопераційний',
      inPatientPostSurgical: 'Стаціонарний післяопераційний',
      rehabilitation: 'Реабілітація та призначення/вибір допоміжних засобів',
      preProsthetic: 'Допротезна реабілітація (для користувачів протезів)',
      prostheticFitting: 'Вибір постачальника протезів та протезування',
      prostheticTraining: 'Навчання користування протезом',
      communityReintegration: 'Суспільна реінтеграція (можливе перенавчання тощо)',
      step5Title: 'З якого ви регіону?',
      step5Subtitle: 'Це допомагає нам пріоритезувати клініки та ресурси у вашому районі.',
      step6Title: 'Додаткова інформація',
      step6Subtitle: 'Поділіться іншими деталями, які можуть допомогти нам надати кращу підтримку (необов\'язково).',
      additionalLabel: 'Додаткові коментарі або занепокоєння',
      additionalPlaceholder: 'Наприклад: проблеми з мобільністю, житлова ситуація, підтримка сім\'ї, потреби у працевлаштуванні...',
      back: 'Назад',
      next: 'Далі',
      complete: 'Завершити',
      notAuthenticated: 'Не авторизовано',
      notAuthenticatedDesc: 'Будь ласка, увійдіть, щоб зберегти вашу оцінку.',
      assessmentComplete: 'Оцінку завершено',
      assessmentCompleteDesc: 'Ваш персоналізований план збережено.',
      errorSaving: 'Помилка збереження',
      errorSavingDesc: 'Виникла проблема зі збереженням вашої оцінки. Спробуйте ще раз.',
    },
    resources: {
      retakeAssessment: 'Пройти знову',
      yourRecoveryRoadmap: 'Ваш план відновлення',
      sections: 'Розділи',
      resourcesAvailable: 'Ресурси',
      actionSteps: 'Кроки дій',
      yourJourney: 'Ваш персоналізований шлях',
      yourJourneySubtitle: 'Виконуйте ці кроки для навігації вашого відновлення',
      loading: 'Завантаження вашого плану...',
      completeFirst: 'Спочатку пройдіть оцінку',
      completeFirstDesc: 'Щоб створити ваш персоналізований план відновлення, будь ласка, пройдіть опитування.',
      startAssessment: 'Почати оцінку',
      learnMore: 'Дізнатися більше',
      visitWebsite: 'Відвідати сайт',
      yourRegion: 'Ваш регіон',
      nearby: 'Поблизу',
      step: 'Крок',
      criticalPriority: 'Критичний пріоритет',
      highPriority: 'Високий пріоритет',
      onTrack: 'На шляху',
      goodProgress: 'Хороший прогрес',
    },
    dashboard: {
      welcomeBack: 'З поверненням',
      subtitle: 'Ваша персоналізована панель допомоги з протезування',
      yourProfile: 'Ваш профіль',
      name: 'Ім\'я',
      email: 'Електронна пошта',
      languageLabel: 'Мова',
      notSet: 'Не вказано',
      english: 'Англійська',
      ukrainian: 'Українська',
      assessmentStatus: 'Статус оцінки',
      completed: 'Завершено',
      injuryTiming: 'Час травми',
      retakeAssessment: 'Пройти знову',
      noAssessment: 'Ви ще не пройшли оцінку.',
      startAssessment: 'Почати оцінку',
      yourRoadmap: 'Ваш персоналізований план',
      viewRoadmapDesc: 'Переглянути ваш індивідуальний шлях до протезної допомоги',
      viewRoadmap: 'Переглянути план',
    },
    auth: {
      welcomeBack: 'З поверненням',
      createAccount: 'Створити акаунт',
      resetPassword: 'Скинути пароль',
      signInSubtitle: 'Увійдіть, щоб отримати доступ до вашого персоналізованого плану',
      signUpSubtitle: 'Приєднайтесь, щоб отримати персоналізовану допомогу з протезування',
      resetSubtitle: 'Введіть вашу електронну пошту для отримання посилання на скидання',
      fullName: 'Повне ім\'я',
      fullNamePlaceholder: 'Введіть ваше повне ім\'я',
      emailLabel: 'Електронна пошта',
      emailPlaceholder: 'Введіть вашу електронну пошту',
      passwordLabel: 'Пароль',
      passwordPlaceholder: 'Введіть ваш пароль',
      forgotPassword: 'Забули пароль?',
      signIn: 'Увійти',
      signUpBtn: 'Створити акаунт',
      sendResetLink: 'Надіслати посилання',
      noAccount: 'Не маєте акаунту?',
      haveAccount: 'Вже маєте акаунт?',
      signUpLink: 'Зареєструватися',
      signInLink: 'Увійти',
      loginFailed: 'Помилка входу',
      invalidCredentials: 'Невірна електронна пошта або пароль. Спробуйте ще раз.',
      accountExists: 'Акаунт існує',
      accountExistsDesc: 'Акаунт з цією поштою вже існує. Будь ласка, увійдіть.',
      signUpFailed: 'Помилка реєстрації',
      accountCreated: 'Акаунт створено!',
      accountCreatedDesc: 'Ласкаво просимо до Ukraine Prosthetic Aid. Тепер ви маєте доступ до вашої панелі.',
      resetFailed: 'Помилка скидання',
      checkEmail: 'Перевірте пошту',
      checkEmailDesc: 'Якщо акаунт з цією поштою існує, ви отримаєте посилання для скидання пароля.',
    },
    disclaimer: {
      title: 'Важливе застереження',
      body: 'Інформація на цьому сайті не є медичною порадою та надається лише в інформаційних цілях. Завжди консультуйтеся зі спеціалістом перед прийняттям рішень.',
      accept: 'Я розумію',
    },
    notFound: {
      title: '404',
      message: 'Упс! Сторінку не знайдено',
      backHome: 'Повернутися на головну',
    },
    prostheticOptions: {
      title: 'Варіанти протезування',
      titleDiscuss: 'Варіанти протезування для обговорення',
      consultMessage: 'Обговоріть варіанти протезування з вашим лікарем та протезистом. Вони порекомендують відповідні варіанти на основі вашої конкретної ситуації.',
      basedOnSituation: 'На основі вашої ситуації ви можете обговорити ці варіанти з вашим лікарем:',
      notMedicalAdvice: 'Це не медична порада. Завжди консультуйтеся з кваліфікованими медичними працівниками перед прийняттям рішень щодо протезування.',
    },
    regionSelector: {
      searchPlaceholder: 'Пошук регіонів...',
      noResults: 'Не знайдено регіонів за запитом',
      selected: 'Обрано',
    },
  },
};
