import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Download, Loader2 } from "lucide-react";
import { PersonalizedRoadmap } from "@/lib/assessmentLogic";
import { useToast } from "@/hooks/use-toast";
import jsPDF from "jspdf";

interface ExportPDFProps {
  roadmap: PersonalizedRoadmap;
}

const ExportPDF = ({ roadmap }: ExportPDFProps) => {
  const [isExporting, setIsExporting] = useState(false);
  const { toast } = useToast();

  const exportToPDF = async () => {
    setIsExporting(true);
    
    try {
      const pdf = new jsPDF('p', 'mm', 'a4');
      const pageWidth = pdf.internal.pageSize.getWidth();
      const margin = 20;
      let yPosition = 20;
      
      // Helper function to add new page if needed
      const checkPageBreak = (height: number) => {
        if (yPosition + height > 270) {
          pdf.addPage();
          yPosition = 20;
        }
      };

      // Title
      pdf.setFontSize(24);
      pdf.setTextColor(37, 99, 235); // Primary blue
      pdf.text('Your Recovery Roadmap', margin, yPosition);
      yPosition += 15;

      // Urgency Level
      pdf.setFontSize(12);
      pdf.setTextColor(100, 100, 100);
      const urgencyText = `Urgency Level: ${roadmap.urgencyLevel.toUpperCase()}`;
      pdf.text(urgencyText, margin, yPosition);
      yPosition += 10;

      // Summary
      pdf.setFontSize(11);
      pdf.setTextColor(60, 60, 60);
      const summaryLines = pdf.splitTextToSize(roadmap.summary, pageWidth - 2 * margin);
      pdf.text(summaryLines, margin, yPosition);
      yPosition += summaryLines.length * 6 + 10;

      // Timeline
      checkPageBreak(20);
      pdf.setFontSize(12);
      pdf.setTextColor(234, 179, 8); // Accent yellow
      pdf.text('Estimated Timeline:', margin, yPosition);
      pdf.setTextColor(60, 60, 60);
      pdf.text(roadmap.estimatedTimeline, margin + 45, yPosition);
      yPosition += 15;

      // Prosthetic Options
      if (roadmap.prostheticOptions.length > 0) {
        checkPageBreak(30);
        pdf.setFontSize(14);
        pdf.setTextColor(37, 99, 235);
        pdf.text('Recommended Prosthetic Options', margin, yPosition);
        yPosition += 8;
        
        pdf.setFontSize(10);
        pdf.setTextColor(60, 60, 60);
        roadmap.prostheticOptions.forEach((option) => {
          checkPageBreak(8);
          pdf.text(`• ${option}`, margin + 5, yPosition);
          yPosition += 6;
        });
        yPosition += 10;
      }

      // Sections
      roadmap.sections.forEach((section) => {
        checkPageBreak(40);
        
        // Section title
        pdf.setFontSize(14);
        pdf.setTextColor(37, 99, 235);
        pdf.text(section.title, margin, yPosition);
        yPosition += 8;

        // Resources
        section.recommendations.forEach((rec, idx) => {
          checkPageBreak(35);
          
          // Resource title
          pdf.setFontSize(11);
          pdf.setTextColor(40, 40, 40);
          const title = `${idx + 1}. ${rec.resource.title}`;
          pdf.text(title, margin + 5, yPosition);
          yPosition += 6;

          // Priority & Timeframe
          pdf.setFontSize(9);
          pdf.setTextColor(100, 100, 100);
          pdf.text(`Priority: ${rec.priority} | Timeframe: ${rec.timeframe}`, margin + 5, yPosition);
          yPosition += 5;

          // Description
          pdf.setFontSize(9);
          const descLines = pdf.splitTextToSize(rec.resource.description, pageWidth - 2 * margin - 10);
          pdf.text(descLines, margin + 5, yPosition);
          yPosition += descLines.length * 4 + 3;

          // Contact info
          if (rec.resource.contact) {
            pdf.setTextColor(37, 99, 235);
            pdf.text(`Tel: ${rec.resource.contact}`, margin + 5, yPosition);
            yPosition += 4;
          }
          if (rec.resource.website) {
            pdf.setTextColor(37, 99, 235);
            pdf.text(`Web: ${rec.resource.website}`, margin + 5, yPosition);
            yPosition += 4;
          }
          yPosition += 4;
        });
        yPosition += 5;
      });

      // Footer
      checkPageBreak(30);
      pdf.setFontSize(10);
      pdf.setTextColor(100, 100, 100);
      pdf.text('Generated by UPAP - Ukrainian Prosthetics Assistance Program', margin, 280);
      pdf.text(`Date: ${new Date().toLocaleDateString()}`, margin, 285);

      // Save the PDF
      pdf.save('UPAP-Recovery-Roadmap.pdf');

      toast({
        title: "PDF Downloaded",
        description: "Your personalized roadmap has been saved.",
      });
    } catch (error) {
      console.error('PDF export error:', error);
      toast({
        title: "Export Failed",
        description: "Unable to generate PDF. Please try again.",
        variant: "destructive",
      });
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <Button
      onClick={exportToPDF}
      disabled={isExporting}
      variant="outline"
      className="gap-2"
    >
      {isExporting ? (
        <>
          <Loader2 className="h-4 w-4 animate-spin" />
          Generating...
        </>
      ) : (
        <>
          <Download className="h-4 w-4" />
          Download PDF
        </>
      )}
    </Button>
  );
};

export default ExportPDF;
